# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/basto/Downloads/clion-2017.1.1/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/basto/Downloads/clion-2017.1.1/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/basto/Git/PipeRelay

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/basto/Git/PipeRelay

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/basto/Downloads/clion-2017.1.1/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/basto/Downloads/clion-2017.1.1/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/basto/Git/PipeRelay/CMakeFiles /home/basto/Git/PipeRelay/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/basto/Git/PipeRelay/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PipeRelayLib

# Build rule for target.
PipeRelayLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PipeRelayLib
.PHONY : PipeRelayLib

# fast build rule for target.
PipeRelayLib/fast:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/build
.PHONY : PipeRelayLib/fast

#=============================================================================
# Target rules for targets named PipeRelay

# Build rule for target.
PipeRelay: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PipeRelay
.PHONY : PipeRelay

# fast build rule for target.
PipeRelay/fast:
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/build
.PHONY : PipeRelay/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/main.cpp.s
.PHONY : main.cpp.s

src/BaseReader.o: src/BaseReader.cpp.o

.PHONY : src/BaseReader.o

# target to build an object file
src/BaseReader.cpp.o:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/BaseReader.cpp.o
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/BaseReader.cpp.o
.PHONY : src/BaseReader.cpp.o

src/BaseReader.i: src/BaseReader.cpp.i

.PHONY : src/BaseReader.i

# target to preprocess a source file
src/BaseReader.cpp.i:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/BaseReader.cpp.i
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/BaseReader.cpp.i
.PHONY : src/BaseReader.cpp.i

src/BaseReader.s: src/BaseReader.cpp.s

.PHONY : src/BaseReader.s

# target to generate assembly for a file
src/BaseReader.cpp.s:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/BaseReader.cpp.s
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/BaseReader.cpp.s
.PHONY : src/BaseReader.cpp.s

src/Loging/Log.o: src/Loging/Log.cpp.o

.PHONY : src/Loging/Log.o

# target to build an object file
src/Loging/Log.cpp.o:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/Loging/Log.cpp.o
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/Loging/Log.cpp.o
.PHONY : src/Loging/Log.cpp.o

src/Loging/Log.i: src/Loging/Log.cpp.i

.PHONY : src/Loging/Log.i

# target to preprocess a source file
src/Loging/Log.cpp.i:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/Loging/Log.cpp.i
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/Loging/Log.cpp.i
.PHONY : src/Loging/Log.cpp.i

src/Loging/Log.s: src/Loging/Log.cpp.s

.PHONY : src/Loging/Log.s

# target to generate assembly for a file
src/Loging/Log.cpp.s:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/Loging/Log.cpp.s
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/Loging/Log.cpp.s
.PHONY : src/Loging/Log.cpp.s

src/Pipehandler.o: src/Pipehandler.cpp.o

.PHONY : src/Pipehandler.o

# target to build an object file
src/Pipehandler.cpp.o:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/Pipehandler.cpp.o
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/Pipehandler.cpp.o
.PHONY : src/Pipehandler.cpp.o

src/Pipehandler.i: src/Pipehandler.cpp.i

.PHONY : src/Pipehandler.i

# target to preprocess a source file
src/Pipehandler.cpp.i:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/Pipehandler.cpp.i
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/Pipehandler.cpp.i
.PHONY : src/Pipehandler.cpp.i

src/Pipehandler.s: src/Pipehandler.cpp.s

.PHONY : src/Pipehandler.s

# target to generate assembly for a file
src/Pipehandler.cpp.s:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/Pipehandler.cpp.s
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/Pipehandler.cpp.s
.PHONY : src/Pipehandler.cpp.s

src/Reader/PipeReader.o: src/Reader/PipeReader.cpp.o

.PHONY : src/Reader/PipeReader.o

# target to build an object file
src/Reader/PipeReader.cpp.o:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/Reader/PipeReader.cpp.o
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/Reader/PipeReader.cpp.o
.PHONY : src/Reader/PipeReader.cpp.o

src/Reader/PipeReader.i: src/Reader/PipeReader.cpp.i

.PHONY : src/Reader/PipeReader.i

# target to preprocess a source file
src/Reader/PipeReader.cpp.i:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/Reader/PipeReader.cpp.i
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/Reader/PipeReader.cpp.i
.PHONY : src/Reader/PipeReader.cpp.i

src/Reader/PipeReader.s: src/Reader/PipeReader.cpp.s

.PHONY : src/Reader/PipeReader.s

# target to generate assembly for a file
src/Reader/PipeReader.cpp.s:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/Reader/PipeReader.cpp.s
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/Reader/PipeReader.cpp.s
.PHONY : src/Reader/PipeReader.cpp.s

src/Writer/PipeWriter.o: src/Writer/PipeWriter.cpp.o

.PHONY : src/Writer/PipeWriter.o

# target to build an object file
src/Writer/PipeWriter.cpp.o:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/Writer/PipeWriter.cpp.o
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/Writer/PipeWriter.cpp.o
.PHONY : src/Writer/PipeWriter.cpp.o

src/Writer/PipeWriter.i: src/Writer/PipeWriter.cpp.i

.PHONY : src/Writer/PipeWriter.i

# target to preprocess a source file
src/Writer/PipeWriter.cpp.i:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/Writer/PipeWriter.cpp.i
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/Writer/PipeWriter.cpp.i
.PHONY : src/Writer/PipeWriter.cpp.i

src/Writer/PipeWriter.s: src/Writer/PipeWriter.cpp.s

.PHONY : src/Writer/PipeWriter.s

# target to generate assembly for a file
src/Writer/PipeWriter.cpp.s:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/Writer/PipeWriter.cpp.s
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/Writer/PipeWriter.cpp.s
.PHONY : src/Writer/PipeWriter.cpp.s

src/ssh/ReadConfig.o: src/ssh/ReadConfig.cpp.o

.PHONY : src/ssh/ReadConfig.o

# target to build an object file
src/ssh/ReadConfig.cpp.o:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/ssh/ReadConfig.cpp.o
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/ssh/ReadConfig.cpp.o
.PHONY : src/ssh/ReadConfig.cpp.o

src/ssh/ReadConfig.i: src/ssh/ReadConfig.cpp.i

.PHONY : src/ssh/ReadConfig.i

# target to preprocess a source file
src/ssh/ReadConfig.cpp.i:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/ssh/ReadConfig.cpp.i
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/ssh/ReadConfig.cpp.i
.PHONY : src/ssh/ReadConfig.cpp.i

src/ssh/ReadConfig.s: src/ssh/ReadConfig.cpp.s

.PHONY : src/ssh/ReadConfig.s

# target to generate assembly for a file
src/ssh/ReadConfig.cpp.s:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/ssh/ReadConfig.cpp.s
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/ssh/ReadConfig.cpp.s
.PHONY : src/ssh/ReadConfig.cpp.s

src/ssh/Ssh.o: src/ssh/Ssh.cpp.o

.PHONY : src/ssh/Ssh.o

# target to build an object file
src/ssh/Ssh.cpp.o:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/ssh/Ssh.cpp.o
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/ssh/Ssh.cpp.o
.PHONY : src/ssh/Ssh.cpp.o

src/ssh/Ssh.i: src/ssh/Ssh.cpp.i

.PHONY : src/ssh/Ssh.i

# target to preprocess a source file
src/ssh/Ssh.cpp.i:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/ssh/Ssh.cpp.i
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/ssh/Ssh.cpp.i
.PHONY : src/ssh/Ssh.cpp.i

src/ssh/Ssh.s: src/ssh/Ssh.cpp.s

.PHONY : src/ssh/Ssh.s

# target to generate assembly for a file
src/ssh/Ssh.cpp.s:
	$(MAKE) -f CMakeFiles/PipeRelayLib.dir/build.make CMakeFiles/PipeRelayLib.dir/src/ssh/Ssh.cpp.s
	$(MAKE) -f CMakeFiles/PipeRelay.dir/build.make CMakeFiles/PipeRelay.dir/src/ssh/Ssh.cpp.s
.PHONY : src/ssh/Ssh.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PipeRelayLib"
	@echo "... PipeRelay"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/BaseReader.o"
	@echo "... src/BaseReader.i"
	@echo "... src/BaseReader.s"
	@echo "... src/Loging/Log.o"
	@echo "... src/Loging/Log.i"
	@echo "... src/Loging/Log.s"
	@echo "... src/Pipehandler.o"
	@echo "... src/Pipehandler.i"
	@echo "... src/Pipehandler.s"
	@echo "... src/Reader/PipeReader.o"
	@echo "... src/Reader/PipeReader.i"
	@echo "... src/Reader/PipeReader.s"
	@echo "... src/Writer/PipeWriter.o"
	@echo "... src/Writer/PipeWriter.i"
	@echo "... src/Writer/PipeWriter.s"
	@echo "... src/ssh/ReadConfig.o"
	@echo "... src/ssh/ReadConfig.i"
	@echo "... src/ssh/ReadConfig.s"
	@echo "... src/ssh/Ssh.o"
	@echo "... src/ssh/Ssh.i"
	@echo "... src/ssh/Ssh.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

